version: 2

steps:
  pip_install: &pip_install
    run:
      name: "Installing dependencies"
      command: python -m pip install -r requirements.txt

jobs:
  lint:
    docker:
      - image: "circleci/python:3.7"
    working_directory: "~/repo"
    steps:
      - checkout
      - *pip_install
      - run:
          name: "Linting code"
          command: "pylama"

  linkcheck:
    docker:
      - image: "circleci/python:3.7"
    working_directory: "~/repo"
    steps:
      - checkout
      - *pip_install
      - run:
          name: "Checking external links"
          command: "sphinx-build -nW -b linkcheck . _build"

workflows:
  version: 2
  build:
    jobs:
      - lint
      - linkcheck
